### PR TITLE
Removing unneeded sysinternal tools

### PR DESCRIPTION
**Pull request by mikenowak**
These aren't needed at the provisioning stage, so removing them. If required one can always do `choco istall sysinternals`, but I'd rather not have binaries can't be easily upgraded to never version sticking around on my systems. And I doubt that anyone else would opt for that either.

Also moved `tee.exe` and `psexec.exe`, which are both required for provisioning and called by foreman scripts to `%deployRoot%`, where `wget` and other tools already reside.

### CODE REVIEW

**Comment by mikenowak** [comment]
Added %deployRoot% to the %PATH% as I've noticed that in few places scripts are prefixed with that, and its hard to remember to reference every time.

**Comment by DimmKirr** [comment]
Merging, assuming this is tested

**Comment by mikenowak** [comment]
You've said this has been merged, but it hasn't

**Comment by DimmKirr** [comment]
@mikenowak Sorry, phone git client failed

**Pull request merged**
