### PR TITLE
Use dism variable instead of dism.exe from path to mount wim

### PR DESCRIPTION
**Pull request by derektamsen**

### CODE REVIEW

**Comment by helge000** [comment]
Hello, sorry for the late reply and thanks for this PR!

Please explain the your reasoning in more detail, and see explanation below:

1. It is really hard for me to find the *actual* changes; please take care not to change tabs and line endings. I know, this is very inconsistent, I will try to change it in the future to spaces ect. This should be a separate PR then.
2. I am inclined to close the PR solely based on your commit message because `$dism` *needs* to be definable and cannot just use the path. This is due to the fact the installed `dism.exe` supports Windows versions up to your running version *only*. If you prepare, say, Windows 10 on on a running Windows 7, you **need** to use the supplied `dism.exe` from Windows AIK.

**Comment by derektamsen** [comment]
1. Sorry about the indentation and trailing line fixes. It was automatic when I saved the file with Atom. This project is quite difficult to edit with a modern editor due to the mixed indentation styles and trailing spaces.
2. Understood. My intention was to use the `$dism` variable defined through https://github.com/kireevco/wimaging/blob/master/inc/Params.ps1#L48 instead of hard coding the utility to the `dism.exe` resolved from `$PATH`. This should result in the correct tool being called to mount the disk image instead of the hard coded version that ships with the version of windows that is being used to create the distribution.

I will update this request with only the `$dism` change so it is easier to review.

**Comment by MattzFiber** [comment]
Would be awesome if we could push this though, see an issue open for it too.

**Comment by derektamsen** [comment]
This would resolve #42

**Comment by helge000** [comment]
Hi guys, sorry for the delay and thanks for the fix - @derektamsen!

**Pull request merged**
