### PR TITLE
Adding support for Windows 7

### PR DESCRIPTION
**Pull request by mikenowak**
Adding support for Windows 7 as discussed  #7.

### CODE REVIEW

**Comment by mikenowak** [comment]
Verified to work on my end -  you can go ahead and merge.

I've also added ISO file support, so that instead of keeping yet another copy of the OS in the sources directory, ISO could be used to populate install and images.

Let me know if you have any questions.

**Comment by DimmKirr** [comment]
Thank you.

Can I please ask you to update read me or let me know what was not accurate or unclear in there to make everything work?

Also, add some documentation for ISO part?

Thanks!

**Comment by mikenowak** [comment]
The ISO documentation is done now.

Re the unclear documentation I think the challenge is that your readme.md starts with "Create minimal updated install.wim image from scratch:" which pretty much confused me and made me believe that winpe was required to set that up. Perhaps you could point out that using winpe is optional and really boot.wim from the install media would do perfectly fine in most cases.

`

**Comment by mikenowak** [comment]
I will refactor this slightly and resubmit

**Pull request closed without merging**
