### PR TITLE
Powershell and windows 10

### PR DESCRIPTION
**Pull request by thekoma**
Added powershell support integration ( Add-packages.ps1  ).
Added Windows 10 Support

The Powershell Support has been added to support the new implementation of the installation method (Including VNC Server implementation from tightvnc released in GPL).

This Release will support headless installation and foreman server autodiscovery (via TFTP) see
https://github.com/koma85/wimaging-tools <- installation scripts + vnc
and
https://github.com/koma85/foreman-wimaging <- modified pxe and anti bootloop

### CODE REVIEW

**Comment by helge000** [comment]
Thanks @koma85; I am working at the same thing right now; did mostly the same things.

Can you pls. reopen this PR:
1. Squash 92fb955 and 6df5ee9 in one commit
2. Be sure to not include 0fd5c5d

If you like, open 0fd5c5d in a separate PR; but I am very reluctant to merge it. We can discuss this in detail if you reopen it; but I want to keep the boot.wim as small as possible and stick only to the bare minimum of functions.

Reasons:
- TFTP is very inefficient (= slow)
- boot.wim needs to fit in memory

I would rather add dig and go with a service record discovery (I will merge this together with Windows 10)

**Comment by thekoma** [comment]
Could you please reach me in #theforeman@freenode ? I would like to explain to you the powershell choise.

**Comment by thekoma** [comment]
written on gitter.im . Let me know

**Comment by helge000** [comment]
I'm travailing and have no access to IRC currently (blocked ports). Further, I'd prefer code related discussions on GitHub, since they are not 'lost'. Just repen the PR and and we can start?

I also see many reasons to use powershell:
- The Future™
- Get rid of awkward DOS code

But: See comments above.

**Pull request closed without merging**
